site :opscode

# opscode
cookbook 'database', github: 'opscode-cookbooks/database'
cookbook 'logwatch', github: 'opscode-cookbooks/logwatch'
cookbook 'logrotate', github: 'opscode-cookbooks/logrotate'
cookbook 'apache2', github: 'opscode-cookbooks/apache2'
cookbook 'rsync', github: 'opscode-cookbooks/rsync'
cookbook 'postfix', github: 'opscode-cookbooks/postfix'
cookbook 'xml', github: 'opscode-cookbooks/xml'
cookbook 'git', github: 'opscode-cookbooks/git'
cookbook 'subversion', github: 'opscode-cookbooks/subversion'
cookbook 'vim', github: 'opscode-cookbooks/vim'
cookbook 'tmux', github: 'opscode-cookbooks/tmux'
cookbook 'sudo', github: 'opscode-cookbooks/sudo'
cookbook 'mongodb', github: 'edelight/chef-mongodb'
cookbook 'aws', github: 'opscode-cookbooks/aws'

# vendor
cookbook 'nodejs', github: 'ptahdunbar/nodejs-cookbook'
cookbook 'npm', github: 'ptahdunbar/npm-cookbook'
cookbook 'wp', github: 'ptahdunbar/wp-cookbook'
cookbook 'php', github: 'ptahdunbar/php-cookbook'
cookbook 'base', github: 'ptahdunbar/base-cookbook'
cookbook 'users', github: 'ptahdunbar/users-cookbook'
cookbook 'web', github: 'ptahdunbar/web-cookbook'
cookbook 'nginx', github: 'ptahdunbar/nginx'
cookbook 'mysql', '~> 4.0.7', github: 'ptahdunbar/mysql-cookbook'
cookbook 'db', '~> 0.0.9', github: 'ptahdunbar/db-cookbook'
cookbook 'mariadb', '~> 0.0.9', github: 'ptahdunbar/mariadb-cookbook'
cookbook 'redisio', github: 'brianbianco/redisio'
cookbook 'timezone-ii', github: 'L2G/timezone-ii'
cookbook 'phpmyadmin', '~> 1.0', :github => 'priestjim/chef-phpmyadmin', :ref => '1.0.6'